services:
  # -----
  # INFRA
  # -----
  cache:
    image: redis:7.2-alpine
    hostname: cache
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"

  # -------------
  # LOAD BALANCER
  # -------------
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "38MB"

  # ---
  # API
  # ---
  api1: &api
    build: .
    hostname: api1
    command: node dist/app.js
    environment:
      - APP_PORT=9999
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - CACHE_HOST=cache
      - CACHE_PORT=6379
    networks:
      - backend
      - payment-processor
    depends_on:
      cache: { condition: service_healthy }
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "40MB"

  api2:
    <<: *api
    hostname: api2

  # ------------------
  # WORKER + WATCHER
  # ------------------
  worker1:
    build: .
    hostname: worker1
    command: node dist/bootstrap.js
    environment:
      - APP_PORT=9999
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - CACHE_HOST=cache
      - CACHE_PORT=6379
    networks:
      - backend
      - payment-processor
    depends_on:
      cache: { condition: service_healthy }
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "180MB"

  # worker2:
  #   <<: *worker
  #   hostname: worker2

networks:
  backend:
    driver: bridge
  payment-processor:
    name: payment-processor
    external: true
